### ISSUE TITLE
Usage of _

### ISSUE THREAD

**Issue by garcianavalon** [ageapps/polymer-style-guide#2]
When should `_`be used as a prefix in function names?

The usual convention is for private or internal methods, but how does that apply in Polymer?

**Comment by ageapps** [comment]
That is an interesting question. I had to think a lot about it, maybe it is not explained clearly in the repo. I didn´t really found much information out there, so i applied a mix of Polymer´s guide and a little of my experience. 

My vision looks like this:
+ observers are always used with `_` prefix. Depending on the complexity it's better to use also suffixes like `_xxxChanged`. The purpose of this is for better legibility.
+ listeners don't need the `_` prefix, instead the prefix `handleXXX` (where XXX is the event which fired the listener) will be used. This is because having all listeners under the same prefix and the event in the description makes them easy to read.
+ Polymer´s component own methods are mostly defined without any prefix like `_`. And it's important to differentiate them from custom ones.
+ Custom methods are not used with prefixes because polymer elements in their catalog never have. That is why the should be well named.

In adition to this, i think that polimer components can also have some kind of layout according to a "hierarchy" (see code layout) and make it even better in terms of scalability and legibility.

Finally i have to say that i have to make more research and be more sure about this conventions. Probably they will change over time when i get more feedback and experience.

**Comment by garcianavalon** [comment]
hmmm, yeah, I don't have a strong opinion on it either.
Doesn't seem weird to have observers with prefix and not listeners? They are kinda the same thing in an logical point of view (reactionary functions to certain events).

I love having de `onXXX`and `XXXChanged` naming convention as it makes code very readable.

**Comment by ageapps** [comment]
After some time reviewing code in the PolymerElements' code,  i can´t really tell if they have any convention about listener methods. I agree, that if seems weird the convention i took.

Finally, what i can definitely tell is that private methods are always preceded by a '_' and listener methods are usually private because there is no need to expose them to other components. 
I will correct this convention according to that reason.

Thanks for the feedback

**Comment by garcianavalon** [comment]
👍 fair enough
